docker run --rm \
  --name edgex-app-rules-engine \
  --env-file .env \
  --entrypoint /edgex-init/ready_to_run_wait_install.sh \
  --hostname edgex-app-rules-engine \
  --read-only \
  --security-opt no-new-privileges:true \
  --user 2002:2001 \
  --network edgex_edgex-network \
  -v /etc/localtime:/etc/localtime:ro \
  -v edgex_edgex-init:/edgex-init:ro \
  -v /tmp/edgex/secrets/app-rules-engine:/tmp/edgex/secrets/app-rules-engine:ro \
  -e EDGEX_PROFILE=rules-engine \
  -e EDGEX_SECURITY_SECRET_STORE=true \
  -e PROXY_SETUP_HOST=edgex-security-proxy-setup \
  -e SECRETSTORE_HOST=edgex-vault \
  -e SERVICE_HOST=app-rules-engine.edgex.ziti \
  -e SERVICE_PORT=80 \
  -e STAGEGATE_BOOTSTRAPPER_HOST=edgex-security-bootstrapper \
  -e STAGEGATE_BOOTSTRAPPER_STARTPORT=54321 \
  -e STAGEGATE_DATABASE_HOST=edgex-redis \
  -e STAGEGATE_DATABASE_PORT=6379 \
  -e STAGEGATE_DATABASE_READYPORT=6379 \
  -e STAGEGATE_PROXYSETUP_READYPORT=54325 \
  -e STAGEGATE_READY_TORUNPORT=54329 \
  -e STAGEGATE_REGISTRY_HOST=edgex-core-consul \
  -e STAGEGATE_REGISTRY_PORT=8500 \
  -e STAGEGATE_REGISTRY_READYPORT=54324 \
  -e STAGEGATE_SECRETSTORESETUP_HOST=edgex-security-secretstore-setup \
  -e STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT=54322 \
  -e STAGEGATE_WAITFOR_TIMEOUT=60s \
  -e APP_SERVICES_CLIENTS_CORE_METADATA_HOST=core-metadata.edgex.ziti \
  -e APP_SERVICES_CLIENTS_CORE_METADATA_PORT="80" \
  -e APP_SERVICES_CLIENTS_CORE_METADATA_SECURITYOPTIONS_MODE=zerotrust \
  edgexfoundry/app-service-configurable:0.0.0-dev \
  /app-service-configurable -cp=consul.http://edgex-core-consul:8500 --registry